In [5]:
import numpy as np
import pandas as pd

In [8]:
cov_data = pd.read_csv('data/3-5-1-cov.csv')
cov_data.head()

x   y
0  18.5  34
1  18.7  39
2  19.1  41
3  19.7  38
4  21.5  45

In [10]:
x = cov_data['x']
y = cov_data['y']
print(x, y)

n = len(cov_data)
print(n)

x_bar = np.mean(x)
y_bar = np.mean(y)
print(x_bar, y_bar)

0    18.5
1    18.7
2    19.1
3    19.7
4    21.5
5    21.7
6    21.8
7    22.0
8    23.4
9    23.8
Name: x, dtype: float64 0    34
1    39
2    41
3    38
4    45
5    41
6    52
7    44
8    44
9    49
Name: y, dtype: int64
10
21.020000000000003 42.7


In [15]:
cov = np.sum((x - x_bar)*(y - y_bar)) / n
cov

6.9060000000000015

In [17]:
s2_x = np.var(x, ddof=0)
s2_y = np.var(y, ddof=0)

_cov = np.array([
    [s2_x, cov],
    [cov, s2_y],
])

_cov

array([[ 3.2816,  6.906 ],
       [ 6.906 , 25.21  ]])

In [18]:
np.cov(x, y, ddof=0)

array([[ 3.2816,  6.906 ],
       [ 6.906 , 25.21  ]])

In [20]:
pearson = np.cov(x, y, ddof=0) / np.square((s2_x * s2_y))
pearson

array([[0.00047948, 0.00100904],
       [0.00100904, 0.00368346]])

In [ ]:
correlation_matrix = np.array([
    [1, pearson],
    [pearson, 1],
])

In [21]:
rho = cov / np.sqrt(s2_x * s2_y)
round(rho, 3)

0.759

In [22]:
np.corrcoef(x, y) # 상관행렬

array([[1.       , 0.7592719],
       [0.7592719, 1.       ]])

In [23]:
disease = pd.read_csv('data/3-5-2-cross.csv')
print(disease.head())

  sunlight disease
0      yes     yes
1      yes     yes
2      yes     yes
3      yes      no
4      yes      no


In [24]:
cross_1 = pd.crosstab(
    disease['sunlight'],
    disease['disease'],
)

print(cross_1)

disease   no  yes
sunlight         
no         2    8
yes        7    3


In [26]:
shoes = pd.read_csv('data/3-5-3-cross2_korean.csv')
print(shoes.head())

   store color  sales
0  seoul  blue     10
1  seoul   red     15
2  busan  blue     13
3  busan   red      9


In [27]:
cross_2 = pd.pivot_table(
    data=shoes,
    values='sales',
    aggfunc='sum',
    index='store',
    columns='color'
)

print(cross_2)

color  blue  red
store           
busan    13    9
seoul    10   15


In [31]:
cross_3 = pd.pivot_table(
    data=shoes,
    values='sales',
    aggfunc='sum',
    index='color',
    columns='store'
)

cross_3

store  busan  seoul
color              
blue      13     10
red        9     15